# This represents the parameters of usb camera

uint32  brightness 							# 0 - 255
uint32  contrast                            # 0 - 255
uint32  saturation                          # 0 - 255
uint32  sharpness                           # 0 - 255
uint32  gain                                # 0 - 255
bool    focus_automatic_continuous          #
int32   focus_absolute                      # -1 - 255
uint32  auto_exposure                       #
uint32  exposure_time_absolute              # 3 - 2047
bool    white_balance_automatic             #
uint32  white_balance_temperature           # 4000 - 6500
